# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(allow_unicode=True, default='', unique=True)),
                ('calories', models.PositiveIntegerField()),
                ('abv', models.DecimalField(decimal_places=1, max_digits=3)),
                ('style', models.CharField(default="It's a beer", max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('glass_type', models.CharField(max_length=256)),
            ],
        ),
    ]
