# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybeerapp', '0003_auto_20170828_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glass',
            name='beer',
        ),
        migrations.AddField(
            model_name='beer',
            name='glass',
            field=models.ManyToManyField(to='mybeerapp.Glass'),
        ),
    ]
