# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybeerapp', '0003_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='bottle_style',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='palate',
        ),
    ]
