# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybeerapp', '0004_auto_20170912_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
