# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mybeerapp', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='mybeerapp.Beer'),
        ),
    ]
