# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybeerapp', '0005_beer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
    ]
