# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybeerapp', '0008_auto_20170913_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
